version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: stplus_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: stplus_db
      MYSQL_USER: stplus_user
      MYSQL_PASSWORD: stplus_password
      TZ: Asia/Bangkok
    ports:
      - "3306:3306"
    volumes:
      - stplus_db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: stplus_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: rootpassword
      UPLOAD_LIMIT: 300M
    ports:
      - "8080:80"
    depends_on:
      - mariadb

  backend:
    build: ./stplus-backend
    container_name: stplus_backend
    restart: always
    working_dir: /app/stplus-backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - mariadb

volumes:
  stplus_db_data: