// 📚 ที่เดียวสำหรับรายการ icon ที่ใช้เลือกให้ "กลุ่มเมนู"/"สิทธิ์การใช้งาน" ทั้งระบบ
// รวมมาจากของเดิมที่เคยพิมพ์ซ้ำกันอยู่ 3 ที่ (AddPermissionDialog.tsx, EditPermissionDialog.tsx,
// AppLayout.tsx) — แก้/เพิ่ม icon ใหม่ที่ไฟล์นี้ที่เดียวพอ ทุกจุดที่ import จะเห็นตรงกันเสมอ
import {
  LayoutDashboard,
  PieChart,
  LineChart,
  Package,
  PackagePlus,
  PackageMinus,
  Box,
  Archive,
  Barcode,
  Tags,
  Store,
  ShoppingCart,
  Receipt,
  Truck,
  Wallet,
  Banknote,
  CreditCard,
  Users,
  SquareUser,
  Building2,
  Briefcase,
  FileText,
  FileSpreadsheet,
  ClipboardList,
  Printer,
  History,
  Settings,
  FolderKey,
  Shield,
  ShieldCheck,
  Key,
  Bell,
  Wrench,
  Hammer,
  Network,
  FolderKanban,
  Database,
  Monitor,
  Laptop,
  HardHat,
  BookUser,
  Drill,
  FireExtinguisher,
  Spotlight,
  type LucideIcon,
} from "lucide-react";

export const MENU_ICONS: { id: string; icon: LucideIcon; label: string }[] = [
  {
    id: "LayoutDashboard",
    icon: LayoutDashboard,
    label: "หน้าหลัก (Dashboard)",
  },
  { id: "PieChart", icon: PieChart, label: "รายงานสถิติ (Pie Chart)" },
  { id: "LineChart", icon: LineChart, label: "กราฟแนวโน้ม (Line Chart)" },
  { id: "Package", icon: Package, label: "สินค้าทั้งหมด (Products)" },
  { id: "PackagePlus", icon: PackagePlus, label: "รับสินค้าเข้า (Stock In)" },
  {
    id: "PackageMinus",
    icon: PackageMinus,
    label: "เบิกสินค้าออก (Stock Out)",
  },
  { id: "Box", icon: Box, label: "กล่อง/บรรจุภัณฑ์ (Box)" },
  { id: "Archive", icon: Archive, label: "คลังจัดเก็บ (Archive)" },
  { id: "Barcode", icon: Barcode, label: "บาร์โค้ด (Barcode)" },
  { id: "Tags", icon: Tags, label: "หมวดหมู่/ป้ายกำกับ (Tags)" },
  { id: "Store", icon: Store, label: "ร้านค้า/หน้าร้าน (Store)" },
  { id: "ShoppingCart", icon: ShoppingCart, label: "สั่งซื้อ/ตะกร้า (Orders)" },
  { id: "Receipt", icon: Receipt, label: "ใบเสร็จ/บิล (Receipts)" },
  { id: "Truck", icon: Truck, label: "จัดส่ง/ขนส่ง (Shipping)" },
  { id: "Wallet", icon: Wallet, label: "กระเป๋าเงิน (Wallet)" },
  { id: "Banknote", icon: Banknote, label: "การเงิน/รายได้ (Finance)" },
  { id: "CreditCard", icon: CreditCard, label: "ชำระเงิน (Payment)" },
  { id: "Users", icon: Users, label: "พนักงาน/ลูกค้า (Users)" },
  { id: "SquareUser", icon: SquareUser, label: "ข้อมูลส่วนตัว (Profile)" },
  { id: "Building2", icon: Building2, label: "บริษัท/สาขา (Company)" },
  { id: "Briefcase", icon: Briefcase, label: "ธุรกิจ/โปรเจกต์ (Business)" },
  { id: "FileText", icon: FileText, label: "เอกสาร (Documents)" },
  {
    id: "FileSpreadsheet",
    icon: FileSpreadsheet,
    label: "ตารางข้อมูล (Spreadsheet)",
  },
  { id: "ClipboardList", icon: ClipboardList, label: "รายการตรวจสอบ (Tasks)" },
  { id: "Printer", icon: Printer, label: "สั่งพิมพ์ (Printer)" },
  { id: "History", icon: History, label: "ประวัติการทำงาน (History)" },
  { id: "Settings", icon: Settings, label: "ตั้งค่าระบบ (Settings)" },
  { id: "FolderKey", icon: FolderKey, label: "จัดการสิทธิ์ (Roles)" },
  { id: "Shield", icon: Shield, label: "ความปลอดภัย (Shield)" },
  {
    id: "ShieldCheck",
    icon: ShieldCheck,
    label: "ยืนยันความปลอดภัย (Security)",
  },
  { id: "Key", icon: Key, label: "กุญแจ/รหัสผ่าน (Key)" },
  { id: "Bell", icon: Bell, label: "แจ้งเตือน (Notifications)" },
  { id: "Wrench", icon: Wrench, label: "เครื่องมือซ่อม (Wrench)" },
  { id: "Hammer", icon: Hammer, label: "งานซ่อม/ช่าง (Hammer)" },
  { id: "Network", icon: Network, label: "เน็ตเวิร์ค (Network)" },
  { id: "FolderKanban", icon: FolderKanban, label: "ไฟล์โฟลเดอร์ (Job)" },
  { id: "Database", icon: Database, label: "ฐานข้อมูล (Database)" },
  { id: "Monitor", icon: Monitor, label: "จอคอม (Monitor)" },
  { id: "Laptop", icon: Laptop, label: "โน้ตบุ๊ก (Laptop)" },
  { id: "HardHat", icon: HardHat, label: "หมวกเซฟตี้ (HardHat)" },
  { id: "BookUser", icon: BookUser, label: "สมุดรายชื่อ (BookUser)" },
  { id: "Drill", icon: Drill, label: "สว่าน (Drill)" },
  { id: "FireExtinguisher", icon: FireExtinguisher, label: "ถังดับเพลิง (FireExtinguisher)" },
  { id: "Spotlight", icon: Spotlight, label: "ไฟส่องสว่าง (Spotlight)" },
];

// derive จาก MENU_ICONS ตัวเดียวกัน ไม่ต้องพิมพ์ชื่อ icon ซ้ำอีกรอบ
export const MENU_ICON_MAP: Record<string, LucideIcon> = MENU_ICONS.reduce(
  (acc, ic) => {
    acc[ic.id] = ic.icon;
    return acc;
  },
  {} as Record<string, LucideIcon>,
);
