<?php

namespace Database\Seeders;

use App\Models\Company;
use App\Models\Role;
use Illuminate\Database\Seeder;
use Spatie\Permission\PermissionRegistrar;

/**
 * 🆕 [2026-09-15] Role Template มาตรฐาน — "ผู้จัดการ - {กลุ่มเมนู}" / "พนักงาน - {กลุ่มเมนู}" ครบทุกกลุ่มเมนูในระบบ
 * (สร้างจริงผ่านหน้า /roles ของบริษัทเจ้าของระบบ (company_id=1) แล้ว sync สิทธิ์ที่ติดจริงแต่ละ role ตรงลงมาที่นี่
 * — ให้ fresh install มี role template ชุดนี้พร้อมใช้ทันที ไม่ต้องมานั่งสร้าง 30 role เองใหม่)
 *
 * กติกาที่สังเกตได้จากข้อมูลจริง (ไม่ได้ hardcode เป็นโค้ด แค่บันทึกไว้ให้เข้าใจ): role "ผู้จัดการ" ของแต่ละกลุ่ม
 * ได้สิทธิ์ approve_* เพิ่มจาก role "พนักงาน" กลุ่มเดียวกัน ที่เหลือ (view/create/edit/delete) เหมือนกันทุกประการ —
 * เก็บ permission list ตรงจาก DB จริงของแต่ละ role แยกกันแทนการคำนวณกฎนี้ เผื่อมีการปรับสิทธิ์ยกเว้นภายหลังผ่านหน้า /roles
 *
 * Idempotent: firstOrCreate ตาม (name, company_id, guard_name) + givePermissionTo เช็คซ้ำก่อนเสมอ รันซ้ำได้ไม่พัง
 * ไม่ต้อง setPermissionsTeamId() เพราะ role_has_permissions ไม่มีคอลัมน์ team_id (ดู StockOnHandMenuSeeder.php/
 * PriceListMenuSeeder.php ที่ไม่เรียกเช่นกัน) — team_id ใช้กับ model_has_roles (ผูก user เข้า role) เท่านั้น
 *
 * รันแยกได้เองบน production ที่รันไปแล้ว:
 *   php artisan db:seed --class="Database\Seeders\DefaultRoleTemplatesSeeder"
 */
class DefaultRoleTemplatesSeeder extends Seeder
{
    public function run(): void
    {
        $hqCompany = Company::find(1);
        if (!$hqCompany) {
            return;
        }

        $roleDefs = [
            [
                'name' => 'ผู้จัดการ - โครงการ',
                'permissions' => [
                    'create_projects',
                    'delete_projects',
                    'edit_projects',
                    'view_projects',
                ],
            ],
            [
                'name' => 'พนักงาน - โครงการ',
                'permissions' => [
                    'create_projects',
                    'delete_projects',
                    'edit_projects',
                    'view_projects',
                ],
            ],
            [
                'name' => 'ผู้จัดการ - จัดซื้อ',
                'permissions' => [
                    'bt_approve_purchase',
                    'bt_create_goods_receipt',
                    'bt_create_goods_receipt_no_po',
                    'bt_create_purchase',
                    'bt_delete_purchase',
                    'bt_edit_purchase',
                    'stock_in_purchase',
                    'view_contractor_work_orders',
                    'view_purchase',
                ],
            ],
            [
                'name' => 'พนักงาน - จัดซื้อ',
                'permissions' => [
                    'bt_create_goods_receipt',
                    'bt_create_goods_receipt_no_po',
                    'bt_create_purchase',
                    'bt_delete_purchase',
                    'bt_edit_purchase',
                    'stock_in_purchase',
                    'view_contractor_work_orders',
                    'view_purchase',
                ],
            ],
            [
                'name' => 'ผู้จัดการ - งานเช่า',
                'permissions' => [
                    'approve_rental_stock_return',
                    'create_rental_jobs',
                    'create_rental_stock_return',
                    'delete_rental_jobs',
                    'delete_rental_stock_return',
                    'edit_rental_jobs',
                    'edit_rental_stock_return',
                    'view_custom_quotation',
                    'view_rental_jobs',
                    'view_rental_stock_return',
                    'view_stock_issue',
                ],
            ],
            [
                'name' => 'พนักงาน - งานเช่า',
                'permissions' => [
                    'create_rental_jobs',
                    'create_rental_stock_return',
                    'delete_rental_jobs',
                    'delete_rental_stock_return',
                    'edit_rental_jobs',
                    'edit_rental_stock_return',
                    'view_custom_quotation',
                    'view_rental_jobs',
                    'view_rental_stock_return',
                    'view_stock_issue',
                ],
            ],
            [
                'name' => 'ผู้จัดการ - ขาย',
                'permissions' => [
                    'approve_billing_invoice',
                    'approve_cash',
                    'approve_credit_note',
                    'approve_custom_cash',
                    'approve_custom_quotation',
                    'approve_debit_note',
                    'approve_delivery_note',
                    'approve_invoice',
                    'approve_installation_issue',
                    'approve_material_issue',
                    'approve_quotation',
                    'approve_receipt',
                    'approve_stock_issue',
                    'approve_stock_return',
                    'approve_tax_invoice',
                    'create_billing_invoice',
                    'create_cash',
                    'create_credit_note',
                    'create_custom_cash',
                    'create_custom_quotation',
                    'create_debit_note',
                    'create_delivery_note',
                    'create_invoice',
                    'create_installation_issue',
                    'create_material_issue',
                    'create_quotation',
                    'create_receipt',
                    'create_stock_issue',
                    'create_stock_return',
                    'create_tax_invoice',
                    'delete_billing_invoice',
                    'delete_cash',
                    'delete_credit_note',
                    'delete_custom_cash',
                    'delete_custom_quotation',
                    'delete_debit_note',
                    'delete_delivery_note',
                    'delete_invoice',
                    'delete_installation_issue',
                    'delete_material_issue',
                    'delete_quotation',
                    'delete_receipt',
                    'delete_stock_issue',
                    'delete_stock_return',
                    'delete_tax_invoice',
                    'edit_billing_invoice',
                    'edit_cash',
                    'edit_credit_note',
                    'edit_custom_cash',
                    'edit_custom_quotation',
                    'edit_debit_note',
                    'edit_delivery_note',
                    'edit_invoice',
                    'edit_installation_issue',
                    'edit_material_issue',
                    'edit_quotation',
                    'edit_receipt',
                    'edit_stock_issue',
                    'edit_stock_return',
                    'edit_tax_invoice',
                    'view_billing_invoice',
                    'view_cash',
                    'view_credit_note',
                    'view_custom_cash',
                    'view_debit_note',
                    'view_delivery_note',
                    'view_invoice',
                    'view_quotation',
                    'view_receipt',
                    'view_stock_return',
                    'view_tax_invoice',
                ],
            ],
            [
                'name' => 'พนักงาน - ขาย',
                'permissions' => [
                    'create_billing_invoice',
                    'create_cash',
                    'create_credit_note',
                    'create_custom_cash',
                    'create_custom_quotation',
                    'create_debit_note',
                    'create_delivery_note',
                    'create_invoice',
                    'create_installation_issue',
                    'create_material_issue',
                    'create_quotation',
                    'create_receipt',
                    'create_stock_issue',
                    'create_stock_return',
                    'create_tax_invoice',
                    'delete_billing_invoice',
                    'delete_cash',
                    'delete_credit_note',
                    'delete_custom_cash',
                    'delete_custom_quotation',
                    'delete_debit_note',
                    'delete_delivery_note',
                    'delete_invoice',
                    'delete_installation_issue',
                    'delete_material_issue',
                    'delete_quotation',
                    'delete_receipt',
                    'delete_stock_issue',
                    'delete_stock_return',
                    'delete_tax_invoice',
                    'edit_billing_invoice',
                    'edit_cash',
                    'edit_credit_note',
                    'edit_custom_cash',
                    'edit_custom_quotation',
                    'edit_debit_note',
                    'edit_delivery_note',
                    'edit_invoice',
                    'edit_installation_issue',
                    'edit_material_issue',
                    'edit_quotation',
                    'edit_receipt',
                    'edit_stock_issue',
                    'edit_stock_return',
                    'edit_tax_invoice',
                    'view_billing_invoice',
                    'view_cash',
                    'view_credit_note',
                    'view_custom_cash',
                    'view_debit_note',
                    'view_delivery_note',
                    'view_invoice',
                    'view_quotation',
                    'view_receipt',
                    'view_stock_return',
                    'view_tax_invoice',
                ],
            ],
            [
                'name' => 'ผู้จัดการ - งานซ่อม',
                'permissions' => [
                    'bill_repairs',
                    'create_repairs',
                    'delete_repairs',
                    'edit_repairs',
                    'transition_repairs',
                ],
            ],
            [
                'name' => 'พนักงาน - งานซ่อม',
                'permissions' => [
                    'bill_repairs',
                    'create_repairs',
                    'delete_repairs',
                    'edit_repairs',
                    'transition_repairs',
                ],
            ],
            [
                'name' => 'ผู้จัดการ - งานติดตั้ง',
                'permissions' => [
                    'create_installations',
                    'delete_installations',
                    'edit_installations',
                    'transition_installations',
                ],
            ],
            [
                'name' => 'พนักงาน - งานติดตั้ง',
                'permissions' => [
                    'create_installations',
                    'delete_installations',
                    'edit_installations',
                    'transition_installations',
                ],
            ],
            [
                'name' => 'ผู้จัดการ - คลังสินค้า',
                'permissions' => [
                    'approve_loan_issue',
                    'approve_loan_return',
                    'approve_packing_list',
                    'create_loan_issue',
                    'create_loan_return',
                    'create_packing_list',
                    'delete_loan_issue',
                    'delete_loan_return',
                    'delete_packing_list',
                    'edit_loan_issue',
                    'edit_loan_return',
                    'edit_packing_list',
                    'export_price_lists',
                    'export_products',
                    'import_price_lists',
                    'import_products',
                    'manage_categories',
                    'manage_price_lists',
                    'manage_products',
                    'manage_units',
                    'manage_warehouses',
                    // 🗑️ [2026-09-17] ลบ menu_stock_in/menu_stock_out ตามที่ผู้ใช้ยืนยัน — permission ถูกลบออก
                    // จากฐานข้อมูลแล้ว (ไม่มีหน้าเพจรองรับ) ถ้าปล่อยชื่อไว้ตรงนี้ givePermissionTo() ด้านล่างจะ
                    // throw PermissionDoesNotExist ตอนรัน seeder นี้ซ้ำ
                    'menu_stock_transfer',
                    'stock_adjustment',
                    'view_loan_issue',
                    'view_loan_return',
                    'view_installation_issue',
                    'view_material_issue',
                    'view_movements',
                    'view_packing_list',
                    'view_price_lists',
                    'view_products',
                    'view_stock_on_hand',
                ],
            ],
            [
                'name' => 'พนักงาน - คลังสินค้า',
                'permissions' => [
                    'create_loan_issue',
                    'create_loan_return',
                    'create_packing_list',
                    'delete_loan_issue',
                    'delete_loan_return',
                    'delete_packing_list',
                    'edit_loan_issue',
                    'edit_loan_return',
                    'edit_packing_list',
                    'export_price_lists',
                    'export_products',
                    'import_price_lists',
                    'import_products',
                    'manage_categories',
                    'manage_price_lists',
                    'manage_products',
                    'manage_units',
                    'manage_warehouses',
                    'menu_stock_transfer',
                    'stock_adjustment',
                    'view_loan_issue',
                    'view_loan_return',
                    'view_installation_issue',
                    'view_material_issue',
                    'view_movements',
                    'view_packing_list',
                    'view_price_lists',
                    'view_products',
                    'view_stock_on_hand',
                ],
            ],
            [
                'name' => 'ผู้จัดการ - ผู้ติดต่อ',
                'permissions' => [
                    'create_contacts',
                    'delete_contacts',
                    'edit_contacts',
                    'export_contacts',
                    'import_contacts',
                    'view_contacts',
                ],
            ],
            [
                'name' => 'พนักงาน - ผู้ติดต่อ',
                'permissions' => [
                    'create_contacts',
                    'delete_contacts',
                    'edit_contacts',
                    'export_contacts',
                    'import_contacts',
                    'view_contacts',
                ],
            ],
            [
                'name' => 'ผู้จัดการ - ผู้รับเหมา',
                'permissions' => [
                    'approve_contractor_work_orders',
                    'create_contractor_work_orders',
                    'delete_contractor_work_orders',
                    'edit_contractor_work_orders',
                ],
            ],
            [
                'name' => 'พนักงาน - ผู้รับเหมา',
                'permissions' => [
                    'create_contractor_work_orders',
                    'delete_contractor_work_orders',
                    'edit_contractor_work_orders',
                ],
            ],
            [
                'name' => 'ผู้จัดการ - สัญญาราชการ',
                'permissions' => [
                    'create_government_contracts',
                    'delete_government_contracts',
                    'edit_government_contracts',
                    'view_government_contracts',
                ],
            ],
            [
                'name' => 'พนักงาน - สัญญาราชการ',
                'permissions' => [
                    'create_government_contracts',
                    'delete_government_contracts',
                    'edit_government_contracts',
                    'view_government_contracts',
                ],
            ],
            [
                'name' => 'ผู้จัดการ - หน้าหลัก',
                'permissions' => [
                    '/',
                ],
            ],
            [
                'name' => 'พนักงาน - หน้าหลัก',
                'permissions' => [
                    '/',
                ],
            ],
            [
                'name' => 'ผู้จัดการ - งานบริการ',
                'permissions' => [
                    'view_installation_issue',
                    'view_installations',
                    'view_repairs',
                ],
            ],
            [
                'name' => 'พนักงาน - งานบริการ',
                'permissions' => [
                    'view_installation_issue',
                    'view_installations',
                    'view_repairs',
                ],
            ],
            [
                'name' => 'ผู้จัดการ - สินทรัพย์ถาวร',
                'permissions' => [
                    'manage_assets',
                ],
            ],
            [
                'name' => 'พนักงาน - สินทรัพย์ถาวร',
                'permissions' => [
                    'manage_assets',
                ],
            ],
            [
                'name' => 'ผู้จัดการ - รายงาน',
                'permissions' => [
                    'view_reports',
                    'view_reports_ap_aging',
                    'view_reports_ar_aging',
                    'view_reports_asset_maintenance_due',
                    'view_reports_asset_list',
                    'view_reports_executive',
                    'view_reports_frequently_repaired_products',
                    'view_reports_installations',
                    'view_reports_installations_by_project',
                    'view_reports_inventory',
                    'view_reports_low_stock',
                    'view_reports_overdue_rentals',
                    'view_reports_po_backorder',
                    'view_reports_project_profitability',
                    'view_reports_purchase_summary',
                    'view_reports_purchases',
                    'view_reports_quotation_conversion',
                    'view_reports_rental_jobs',
                    'view_reports_repair_cost_trend',
                    'view_reports_repair_turnaround',
                    'view_reports_repairs',
                    'view_reports_sales',
                    'view_reports_sales_all',
                    'view_reports_sales_by_salesperson',
                    'view_reports_sales_margin',
                    'view_reports_sales_trend',
                    'view_reports_slow_moving_stock',
                    'view_reports_stock_by_warehouse',
                    'view_reports_stock_movement_ledger',
                    'view_reports_supplier_price_comparison',
                    'view_reports_top_customers',
                    'view_reports_top_suppliers',
                    'view_reports_warranty_expiry',
                ],
            ],
            [
                'name' => 'พนักงาน - รายงาน',
                'permissions' => [
                    'view_reports',
                    'view_reports_ap_aging',
                    'view_reports_ar_aging',
                    'view_reports_asset_maintenance_due',
                    'view_reports_asset_list',
                    'view_reports_executive',
                    'view_reports_frequently_repaired_products',
                    'view_reports_installations',
                    'view_reports_installations_by_project',
                    'view_reports_inventory',
                    'view_reports_low_stock',
                    'view_reports_overdue_rentals',
                    'view_reports_po_backorder',
                    'view_reports_project_profitability',
                    'view_reports_purchase_summary',
                    'view_reports_purchases',
                    'view_reports_quotation_conversion',
                    'view_reports_rental_jobs',
                    'view_reports_repair_cost_trend',
                    'view_reports_repair_turnaround',
                    'view_reports_repairs',
                    'view_reports_sales',
                    'view_reports_sales_all',
                    'view_reports_sales_by_salesperson',
                    'view_reports_sales_margin',
                    'view_reports_sales_trend',
                    'view_reports_slow_moving_stock',
                    'view_reports_stock_by_warehouse',
                    'view_reports_stock_movement_ledger',
                    'view_reports_supplier_price_comparison',
                    'view_reports_top_customers',
                    'view_reports_top_suppliers',
                    'view_reports_warranty_expiry',
                ],
            ],
            [
                'name' => 'ผู้จัดการ - ตั้งค่าระบบ',
                'permissions' => [
                    'manage_company',
                    'manage_permissions',
                    'manage_roles',
                    'manage_users',
                    'view_activity_log',
                ],
            ],
            [
                'name' => 'พนักงาน - ตั้งค่าระบบ',
                'permissions' => [
                    'manage_company',
                    'manage_permissions',
                    'manage_roles',
                    'manage_users',
                    'view_activity_log',
                ],
            ],
        ];

        foreach ($roleDefs as $def) {
            $role = Role::firstOrCreate(
                ['name' => $def['name'], 'company_id' => $hqCompany->id, 'guard_name' => 'web'],
                ['is_company_admin' => false],
            );
            foreach ($def['permissions'] as $permName) {
                if (!$role->hasPermissionTo($permName)) {
                    $role->givePermissionTo($permName);
                }
            }
        }

        app(PermissionRegistrar::class)->forgetCachedPermissions();
    }
}
